# O objetivo aqui é ler os diferentes datasets guardados nos diferentes diretórios e juntar tudo num SUPER Data Set

In [93]:
import pandas as pd
import unicodedata

In [94]:
from google.colab import drive

#Change the Path according to your drive before executing the next cells

In [95]:
path = "/content/drive/MyDrive/Colab Notebooks/PfDS/"

In [96]:

drive.mount('/content/drive')

df_energy_household = pd.read_csv(
    path + "/Carlota/energy_household.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [97]:
df_energy_household

,Unnamed: 0,ano,distrito,concelho,energia_ativa_kwh,cpes,kwh_por_cpe
0,0,2022,Aveiro,Albergaria-a-Velha,5.060819e+07,14082,3593.821190
1,1,2022,Aveiro,Anadia,5.757067e+07,17134,3360.024863
2,2,2022,Aveiro,Arouca,4.187300e+07,12546,3337.557389
3,3,2022,Aveiro,Aveiro,1.793955e+08,50830,3529.322895
4,4,2022,Aveiro,Castelo de Paiva,2.649272e+07,7946,3334.094891
...,...,...,...,...,...,...,...
1107,1107,2025,Évora,Reguengos de Monsaraz,2.303527e+07,7335,3140.459276
1108,1108,2025,Évora,Vendas Novas,2.184646e+07,7092,3080.437505
1109,1109,2025,Évora,Viana do Alentejo,1.221777e+07,3801,3214.356716
1110,1110,2025,Évora,Vila Viçosa,1.476070e+07,4994,2955.686702
1111,1111,2025,Évora,Évora,1.243926e+08,33340,3731.031478

In [98]:
df_energy_household = df_energy_household.drop(columns=['Unnamed: 0'])

In [99]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df_houseHold= pd.read_parquet(
    path +"HouseHold Income Luís :)/household_income_w_forecast.parquet"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [100]:
df_houseHold

     municipio  year        income
0     Abrantes  2015  15108.000000
1     Abrantes  2016  15609.000000
2     Abrantes  2017  16014.000000
3     Abrantes  2018  16574.000000
4     Abrantes  2019  17115.000000
...        ...   ...           ...
4039    Óbidos  2022  19046.666464
4040    Óbidos  2023  20952.704234
4041    Óbidos  2024  23464.646970
4042    Óbidos  2025  25454.088586
4043    Óbidos  2026  27405.426161

[4044 rows x 3 columns]

In [101]:
df_energy_prices= pd.read_parquet(
  path + "Energy Prices Simão :)/energy_prices.parquet"
)

In [102]:
df_energy_prices

     Ano       Banda  Preco_Final
3   2025  Banda - DC     0.241239
8   2024  Banda - DC     0.252580
11  2023  Banda - DC     0.218317
16  2022  Banda - DC     0.221047
24  2021  Banda - DC     0.212954
25  2020  Banda - DC     0.212646
30  2019  Banda - DC     0.216550
39  2018  Banda - DC     0.226961
40  2017  Banda - DC     0.225715
45  2016  Banda - DC     0.232400

In [103]:
list(df_energy_prices['Banda'].unique())

['Banda - DC']

In [104]:
df_median_age= pd.read_excel(
    path + "Median Age/idade_mediana_por_municipio_1.xlsx"
)

In [105]:
df_median_age

,Concelho,Distrito,População (2023),Idade Mediana (2023)
0,Arcos de Valdevez,Viana do Castelo,20786,54.7
1,Caminha,Viana do Castelo,16324,50.8
2,Melgaço,Viana do Castelo,7607,60.6
3,Monção,Viana do Castelo,17974,54.0
4,Paredes de Coura,Viana do Castelo,8693,51.1
...,...,...,...,...
273,São Brás de Alportel,Faro,11551,47.4
274,Silves,Faro,39226,46.6
275,Tavira,Faro,27767,50.5
276,Vila do Bispo,Faro,5906,48.5
277,Vila Real de Santo António,Faro,19235,47.5

In [106]:
df_energy_eff = pd.read_parquet(path + "Energy Efficiency Madalena :)/Energy_eff.parquet")

In [107]:
df_energy_eff

,Mês de Emissão,Região,NUTS III,Distrito,Concelho,Tipo de Doc / Contexto,Classe Energética,Total de Certificados Emitidos
0,2015,Portugal Continental,Alentejo Central,ÉVORA,ALANDROAL,Edifícios Existentes,A,1
1,2015,Portugal Continental,Alentejo Central,ÉVORA,ALANDROAL,Edifícios Existentes,A+,1
2,2015,Portugal Continental,Alentejo Central,ÉVORA,ALANDROAL,Edifícios Existentes,B,2
3,2015,Portugal Continental,Alentejo Central,ÉVORA,ALANDROAL,Edifícios Existentes,B-,2
4,2015,Portugal Continental,Alentejo Central,ÉVORA,ALANDROAL,Edifícios Existentes,C,1
...,...,...,...,...,...,...,...,...
36194,2025,Região Autónoma da Madeira,Região Autónoma da Madeira,MADEIRA,SANTANA,Edifícios Existentes,B-,2
36195,2025,Região Autónoma da Madeira,Região Autónoma da Madeira,MADEIRA,SANTANA,Edifícios Existentes,C,6
36196,2025,Região Autónoma da Madeira,Região Autónoma da Madeira,MADEIRA,SANTANA,Edifícios Existentes,D,17
36197,2025,Região Autónoma da Madeira,Região Autónoma da Madeira,MADEIRA,SANTANA,Edifícios Existentes,E,17
36198,2025,Região Autónoma da Madeira,Região Autónoma da Madeira,MADEIRA,SANTANA,Edifícios Existentes,F,6

We are going to multiply the energy prices for the energy consumption to obtain the annual energy expenditure per cpe.

In [108]:
len(df_houseHold['municipio'].unique())

335

In [109]:
df_energy_expenditure = df_energy_household.merge(df_energy_prices[['Ano', 'Preco_Final']],left_on='ano',right_on='Ano',how='left')

In [110]:
df_energy_expenditure = df_energy_expenditure.drop(columns=['Ano'])

In [111]:
df_energy_expenditure['annual_expenditure'] = (df_energy_expenditure['kwh_por_cpe'] * df_energy_expenditure['Preco_Final'])

In [112]:
df_energy_expenditure

,ano,distrito,concelho,energia_ativa_kwh,cpes,kwh_por_cpe,Preco_Final,annual_expenditure
0,2022,Aveiro,Albergaria-a-Velha,5.060819e+07,14082,3593.821190,0.221047,794.404827
1,2022,Aveiro,Anadia,5.757067e+07,17134,3360.024863,0.221047,742.724757
2,2022,Aveiro,Arouca,4.187300e+07,12546,3337.557389,0.221047,737.758380
3,2022,Aveiro,Aveiro,1.793955e+08,50830,3529.322895,0.221047,780.147647
4,2022,Aveiro,Castelo de Paiva,2.649272e+07,7946,3334.094891,0.221047,736.993004
...,...,...,...,...,...,...,...,...
1107,2025,Évora,Reguengos de Monsaraz,2.303527e+07,7335,3140.459276,0.241239,757.601354
1108,2025,Évora,Vendas Novas,2.184646e+07,7092,3080.437505,0.241239,743.121760
1109,2025,Évora,Viana do Alentejo,1.221777e+07,3801,3214.356716,0.241239,775.428301
1110,2025,Évora,Vila Viçosa,1.476070e+07,4994,2955.686702,0.241239,713.026997
1111,2025,Évora,Évora,1.243926e+08,33340,3731.031478,0.241239,900.070420

We are going to uniformize the names of the portuguese concelhos and districts in the different data frames

In [113]:
drive.mount('/content/drive')

df_municipios_distritos = pd.read_csv(
    path + "municipios_distritos_portugal.csv"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [114]:
df_municipios_distritos

              municipio distrito_ou_regiao_autonoma
0              Abrantes                    Santarem
1                Agueda                      Aveiro
2       Aguiar da Beira                      Guarda
3             Alandroal                       Evora
4    Albergaria-a-Velha                      Aveiro
..                  ...                         ...
303             Vimioso                    Braganca
304             Vinhais                    Braganca
305               Viseu                       Viseu
306              Vizela                       Braga
307             Vouzela                       Viseu

[308 rows x 2 columns]

First, we imported the dataframe which will be the source of truth for the names of municipios and districts.

In [115]:
df_municipios_distritos.isnull().values.any()

np.False_

In [116]:
df_energy_expenditure.isnull().values.any()

np.False_

In [117]:
df_energy_eff.isnull().values.any()

np.False_

In [118]:
df_houseHold.isnull().values.any()

np.False_

In [119]:
df_median_age.isnull().values.any()

np.False_

In [120]:
def normalize(column):

    normalized_values = []

    for x in column:
        x = str(x).strip().lower() #converts text to lowercase

        x= unicodedata.normalize("NFKD", x)
        x = "".join(c for c in x if not unicodedata.combining(c)) #removes accents

        x = x.replace("-", " ") #deletes hiphens
        x = " ".join(x.split()) #deletes extra spaces

        normalized_values.append(x)

    return normalized_values

In [124]:
df_municipios_distritos["municipio_limpo"] = normalize(df_municipios_distritos["municipio"])
df_energy_expenditure["concelho_limpo"] = normalize(df_energy_expenditure["concelho"])
df_median_age["Concelho_limpo"]=normalize(df_median_age["Concelho"])
df_houseHold["municipio_limpo"]=normalize(df_houseHold["municipio"])
df_municipios_distritos["distrito_limpo"] = normalize(df_municipios_distritos["distrito_ou_regiao_autonoma"])
df_energy_expenditure["distrito_limpo"] = normalize(df_energy_expenditure["distrito"])
df_median_age["Distrito_limpo"]=normalize(df_median_age["Distrito"])

We applied the normalize function to all the concellho/municipio columns of our dataframes.

In [ ]:
municipios_ref = df_municipios_distritos[
    ["municipio_limpo", "distrito_limpo", "municipio", "distrito_ou_regiao_autonoma"]
]

In [123]:
df_energy_expenditure = df_energy_expenditure.merge(df_municipios_distritos[["municipio_limpo", "municipio", "distrito_ou_regiao_autonoma"]],left_on="concelho_limpo",right_on="municipio_key",how="left"
)

KeyError: 'municipio_key'

We merged the dataframe with the correct concelho/municioio (df_municipios_distritos) values to each dataframe